version: "3"

services:
  db:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    command: ["executable", "arg"]
    depends_on:
      - db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file: # used in the host machine
      - ./api/.env.local.prod
    environment: # used inside the container
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    ports:
      - 3000:3000
      - 5555:5555 # prisma studio

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env.local.prod
    ports:
      - 5173:5173

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    env_file:
      - ./admin/.env.local.prod
    ports:
      - 6173:6173

volumes:
  postgres:
