version: "3"

services:
  db:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    command: ["executable", "arg"]
    volumes:
      - ./db/servers.json:/pgadmin4/servers.json
    depends_on:
      - db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.local
      target: development
    depends_on:
      - db
    env_file: # used in the host machine
      - ./api/.env.local
    environment: # used inside the container
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    command: npm run start:dev
    ports:
      - 3000:3000
      - 5555:5555 # prisma studio
      - 9230:9230 # debug port server
    volumes:
      - ./api/:/usr/src/app/
      - /usr/src/app/node_modules

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.local
    env_file:
      - ./app/.env.local
    ports:
      - 5173:5173
    volumes:
      - ./app/:/usr/src/app/
      - /usr/src/app/node_modules

volumes:
  postgres:
