version: "3"

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./postgres/.env.local
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./pgadmin/.env.local
    ports:
      - 5050:80
    command: ["executable", "arg"]
    depends_on:
      - postgres

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.local
    depends_on:
      - postgres
    env_file:
      - ./api/.env.local
    ports:
      - 3000:3000
      - 5555:5555 # prisma studio
      - 9230:9230 # debug port
    volumes:
      - ./api/:/usr/src/app/
      - /usr/src/app/node_modules

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.local
    env_file:
      - ./app/.env.local
    ports:
      - 5173:5173
    volumes:
      - ./app/:/usr/src/app/
      - /usr/src/app/node_modules

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.local
    env_file:
      - ./admin/.env.local
    ports:
      - 6173:6173
    volumes:
      - ./admin/:/usr/src/app/
      - /usr/src/app/node_modules

volumes:
  postgres:
