version: "3"

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile.github
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile.github
    restart: always
    ports:
      - 5050:80
    command: ["executable", "arg"]
    depends_on:
      - postgres

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.github
    depends_on:
      - postgres
    ports:
      - 3000:3000

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.github
    ports:
      - 5173:5173

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.github
    ports:
      - 6173:6173

volumes:
  postgres:
