version: "3"

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./postgres/.env.local.prod
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./pgadmin/.env.local.prod
    ports:
      - 5050:80
    command: ["executable", "arg"]
    depends_on:
      - postgres

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./api/.env.local.prod
    ports:
      - 3000:3000
      - 5555:5555 # prisma studio

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env.local.prod
    ports:
      - 5173:5173

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    env_file:
      - ./admin/.env.local.prod
    ports:
      - 6173:6173

volumes:
  postgres:
