FROM node:20.10.0-alpine3.18

# set working directory
WORKDIR /usr/src/app

# install app dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install --silent

# copy project
COPY . .

CMD ["npm", "run" , "dev"]