FROM node:18 AS development


# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Required for Prisma Client to work in the container
RUN apt-get update && apt-get install -y openssl && apt-get install -y netcat

WORKDIR /usr/src/app

COPY --chown=node:node . .
RUN rm -rf node_modules

RUN npm install

RUN npm run prisma:generate 

USER node

ENTRYPOINT ["./init.sh"]
