FROM node:lts-alpine3.18


# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Required for Prisma Client to work in the container
RUN apk update && apk add --no-cache openssl netcat-openbsd


WORKDIR /usr/src/app

COPY --chown=node:node . .

RUN npm install

RUN npm run prisma:generate 

USER node

ENTRYPOINT ["./init.sh"]
